spring.application.name=foodiesapi

# mongodb configuration
spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8080}


# aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketName=foodies28
jwt.secret.key=${JWT_SECRET}

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}


